package org.exoplatform.gamification;

public interface GamificationConstant {

    /** */
    String GAMIFICATION_SOCIAL_ACTIVITY_ADD_NEW_ON_SPACE                            = "GAMIFICATION_SOCIAL_ACTIVITY_ADD_NEW_ON_SPACE_STREAM";
    String GAMIFICATION_SOCIAL_ACTIVITY_ADD_NEW_ON_SPACE_STREAM_MANAGER             = "GAMIFICATION_SOCIAL_ACTIVITY_ADD_NEW_ON_SPACE_STREAM_MANAGER";
    String GAMIFICATION_SOCIAL_ACTIVITY_NEW_ME_ON_MY_STREAM                         = "GAMIFICATION_SOCIAL_ACTIVITY_ADD_NEW_ON_USER_STREAM";
}
